name: Festival
author: Genboy
version: 1.0.6-13-dev2
main: genboy\Festival\Main
load: POSTWORLD
api: [3.0.0, 4.0.0]
website: "https://github.com/genboy/Festival"
commands:
  fe:
    description: "Allows you to manage Festival area's and events."
    usage: "See info: /fe <list/here>; Create area: select 2 positions /fe <pos1/pos2>, then /fe create <AREANAME>; Toggle flags: /fe <FLAGNAME> <AREANAME>; Set commands: /fe command <AREANAME> <add/enter/center/leave> <COMMANDID> <COMMANDSTRING>; (Edit)del command: /fe command <AREANAME> <(edit)/del> <COMMANDID> (<COMMANDSTRING>); Change command event: /fe command <AREANAME> event <COMMANDID> <enter/center/leave>"
    permission: festival.command.fe
permissions:
  festival:
    description: "Allows access to all Festival features."
    default: false
    children:
      festival.access:
        description: "Allows access to editing festival areas and events."
        default: op
      festival.command:
        description: "Allows access to all Festival commands."
        default: false
        children:
          festival.command.fe:
            description: "Allows access to the Festival area command."
            default: op
            children:
              festival.command.fe.pos1:
                description: "Allows access to the Festival pos1 subcommand."
                default: op
              festival.command.fe.pos2:
                description: "Allows access to the Festival pos2 subcommand."
                default: op
              festival.command.fe.create:
                description: "Allows access to the Festival create subcommand."
                default: op
              festival.command.fe.list:
                description: "Allows access to the Festival list subcommand."
                default: op
              festival.command.fe.here:
                description: "Allows access to the Festival here subcommand."
                default: op
              festival.command.fe.tp:
                description: "Allows access to the Festival tp subcommand."
                default: op
              festival.command.fe.desc:
                description: "Allows access to the Festival description subcommand."
                default: op
              festival.command.fe.flag:
                description: "Allows access to the Festival flag subcommand."
                default: op
              festival.command.fe.delete:
                description: "Allows access to the iProtector delete subcommand."
                default: op
              festival.command.fe.whitelist:
                description: "Allows access to the Festival whitelist subcommand."
                default: op
              festival.command.fe.command:
                description: "Allows access to the Festival command subcommand."
                default: op
